# -*- coding: utf-8 -*-
"""Weather Analysis project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1egc73nLcqAmJM0nrj9DLZvEcd3lwrW7n
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()
file_name = list(uploaded.keys())[0]

data = pd.read_csv(file_name)

data

# head

data.head()

# shape
data.shape

#index
data.index

# columns
data.columns

#dtypes
data.dtypes

#unique
data["Weather"].unique()

#nunique
data.nunique()

#count
data.count()

#value_counts
data["Weather"].value_counts()

# info
data.info()

# Find all the  unique 'wind speed' values in the data
data.head(2)

data.nunique()

data['Wind Speed_km/h'].nunique()

data['Wind Speed_km/h'].unique()  # Answer

# Find the no. of times when the 'weather is exactly clear'

data.head(2)

# value_counts
data.Weather.value_counts()

# filtering
data.head(2)
data[data.Weather == 'Clear']

# group by
data.head(2)
data.groupby('Weather').get_group('Clear')  #answer

# find the no. of times when the 'wind speed was exactly 4km/h'

data.head(2)

data[data['Wind Speed_km/h'] == 4]      # answer

#  find out all the null values in the data
data.isnull().sum()

data.notnull().sum()  #answer

# Rename the column “Weather” → “Weather Condition”

data.rename(columns = {'Weather': 'Weather Condition'}, inplace = True)

# What is meant by visibility
data.head(2)

data.Visibility_km.mean()

# What is the standard deviation of “Pressure” in this data
data.Press_kPa.std()

# What is the variance of “Relative Humidity”
data['Rel Hum_%'].var()

# Find all instances when “Snow” was recorded
data['Weather Condition'].value_counts()

data[data['Weather Condition'].str.contains('Snow')]

data[data['Weather Condition'] == 'Snow']

# Find all instances when Wind Speed > 24 and Visibility = 25
data.head(2)

data[(data['Wind Speed_km/h'] > 24  & (data['Visibility_km'] == 25))]

# Mean value of each column grouped by Weather Condition
data.head(2)

data.groupby('Weather Condition').mean(numeric_only=True)

# Minimum and maximum value of each column against each Weather Condition
data.head(2)

data.groupby('Weather Condition').agg(['min', 'max'])

# Show all records where Weather Condition is Fog
data[data['Weather Condition'] == 'Fog']

# Instances when Weather is Clear OR Visibility > 40
data[(data['Weather Condition'] == 'Clear') | (data['Visibility_km'] > 40)]

# Instances when Weather is Clear AND Relative Humidity > 50 OR Visibility > 40
data[((data['Weather Condition'] == 'Clear') & (data['Rel Hum_%'] > 50)) | (data['Visibility_km'] > 40)]